// demos/hero-vue-vapor/app.tsx
import { onMounted, ref } from "vue";
import { Image, Text, View, type NodeMirror } from "@pocketjs/framework/components";
import { animate } from "@pocketjs/framework/animation";
import { createSpriteAnimation } from "@pocketjs/framework/vue-vapor/lifecycle";
import { frameworkName } from "@pocketjs/framework";

const SPINNER_FRAME_STEP = 3;
const SPINNER_FRAMES = [
  "spinner-00.svg",
  "spinner-01.svg",
  "spinner-02.svg",
  "spinner-03.svg",
  "spinner-04.svg",
  "spinner-05.svg",
  "spinner-06.svg",
  "spinner-07.svg",
];

function Stat(props: { label: string; value: string; cls: string }) {
  return (
    <View class="flex-col items-end">
      <Text class={props.cls}>{props.value}</Text>
      <Text class="text-xs text-slate-500 tracking-wide">{props.label}</Text>
    </View>
  );
}

export default () => {
  const count = ref(0);
  const spinnerSrc = createSpriteAnimation(SPINNER_FRAMES, { frameStep: SPINNER_FRAME_STEP });
  let underline: NodeMirror | undefined;

  onMounted(() => {
    if (underline) animate(underline, "width", 210, { dur: 700, easing: "out", delay: 150 });
  });

  return (
    <View class="w-full h-full flex-col justify-between p-5 bg-gradient-to-b from-slate-50 to-slate-100">
      <View class="flex-row items-center justify-between">
        <View class="flex-row items-center gap-3">
          <Image class="w-10 h-10 rounded-lg shadow" src="logo.png" />
          <View class="flex-col">
            <Text class="text-base text-slate-950 font-bold tracking-wide">PocketJS</Text>
            <Text class="text-xs text-slate-500 tracking-wide">{frameworkName()} + RUST + SCEGU</Text>
          </View>
        </View>
        <View class="flex-row gap-4">
          <Stat label="FPS" value="60" cls="text-lg text-emerald-600 font-bold" />
          <Stat label="NODES" value="42" cls="text-lg text-blue-600 font-bold" />
          <Stat label="DRAWS" value="9" cls="text-lg text-amber-600 font-bold" />
        </View>
      </View>

      <View class="flex-col gap-2">
        <Text class="text-xs text-blue-600 tracking-wide">ONE RUST CORE - ONE VUE VAPOR APP</Text>
        <View class="flex-row items-center justify-between">
          <Text class="text-4xl text-slate-950 font-bold">JSX at 60 FPS.</Text>
          <Image class="w-10 h-10" src={spinnerSrc.value} />
        </View>
        <View
          nodeRef={(node) => {
            underline = node ?? undefined;
          }}
          class="h-1 w-0 rounded-full shadow bg-gradient-to-r from-blue-500 to-cyan-500"
          style={{ translateX: count.value * 2 }}
        />
        <Text class="text-sm text-slate-600">
          Flexbox, springs and baked type - running through Vue Vapor.
        </Text>
      </View>

      <View class="flex-row items-center gap-4">
        <View
          class="px-4 py-2 rounded-xl shadow-md bg-blue-600 border-blue-500 focus:bg-blue-500 active:bg-blue-700 transition-colors duration-150"
          focusable
          onPress={() => {
            count.value++;
          }}
        >
          <Text class="text-base text-white font-bold">Press Circle</Text>
        </View>
        <Text class="text-sm text-slate-600">Count: {count.value}</Text>
        {count.value > 3 ? (
          <Text class="text-sm text-emerald-600">Reactive on real hardware.</Text>
        ) : null}
      </View>
    </View>
  );
};

// apps/nsengine/app.tsx
// @title NS Engine — pocketjs guest talking to a NativeScript host
import { createSignal, onMount } from "solid-js";
import { Image, Screen, Text, View } from "@pocketjs/framework/components";
import { runEffect } from "@pocketjs/framework/effects";
import { createSpriteAnimation, onFrame } from "@pocketjs/framework/lifecycle";
import { pumpHostLines } from "./channel.ts";

const SPINNER_FRAMES = [
  "spinner-00.svg",
  "spinner-01.svg",
  "spinner-02.svg",
  "spinner-03.svg",
  "spinner-04.svg",
  "spinner-05.svg",
  "spinner-06.svg",
  "spinner-07.svg",
];

// Bakes the glyphs dynamic host strings may use (digits, punctuation).
const GLYPH_SEED = "0123456789 #:{}\"pong hello from NativeScript,.!?-_iOS via sandboxed realm";

// In a sidecar realm (Direction A) no platform globals exist; when the
// NativeScript runtime is the guest engine (Direction B), the whole iOS
// surface is one identifier away.
declare const UIDevice: { currentDevice: { systemVersion: string } } | undefined;
const platformReach = typeof UIDevice !== "undefined"
  ? `iOS ${UIDevice!.currentDevice.systemVersion} via NativeScript`
  : "sandboxed realm";

function Stat(props: { label: string; value: string; valueClass: string }) {
  return (
    <View class="flex-col flex-1 gap-1 rounded-lg bg-slate-800 p-3 shadow">
      <Text class="text-xs text-slate-400 tracking-wide">{props.label}</Text>
      <Text class={props.valueClass}>{props.value}</Text>
    </View>
  );
}

export default function App() {
  const [reply, setReply] = createSignal("waiting");
  const [hostEvent, setHostEvent] = createSignal("none yet");
  const [count, setCount] = createSignal(0);
  const spinnerSrc = createSpriteAnimation(SPINNER_FRAMES, { frameStep: 5 });

  onFrame(() => pumpHostLines((message) => {
    setHostEvent(String(message["msg"] ?? JSON.stringify(message)));
  }));

  const ping = () => {
    const n = count() + 1;
    setCount(n);
    runEffect("ns.ping", { n }, (result) => setReply(String(result)));
  };

  // Fire one round trip unprompted so the channel proves itself on boot.
  onMount(() => ping());

  return (
    <Screen class="relative flex-col w-full h-full overflow-hidden justify-between p-5 bg-gradient-to-b from-slate-950 to-slate-900">
      <View class="flex-row items-center justify-between">
        <View class="flex-row items-center gap-3">
          <Image class="w-10 h-10 rounded-lg shadow" src="logo.png" />
          <View class="flex-col">
            <Text class="text-base text-white font-bold tracking-wide">
              PocketJS × NativeScript
            </Text>
            <Text class="text-xs text-slate-400 tracking-wide">
              one Rust core · two JS worlds
            </Text>
          </View>
        </View>
        <Image class="w-8 h-8" src={spinnerSrc()} />
      </View>

      <View class="flex-row gap-3">
        <Stat label="guest → host" value={reply()} valueClass="text-xs font-bold text-cyan-400" />
        <Stat label="host → guest" value={hostEvent()} valueClass="text-xs font-bold text-blue-400" />
        <Stat label="platform" value={platformReach} valueClass="text-xs font-bold text-emerald-400" />
      </View>

      <View class="flex-row items-center gap-4">
        <View class="rounded-xl bg-blue-600 px-5 py-2 shadow" focusable onPress={ping}>
          <Text class="text-sm font-bold text-white">Ping host · {count()}</Text>
        </View>
        <View class="h-1 flex-1 rounded bg-gradient-to-r from-blue-500 to-cyan-500" />
      </View>
      <Text class="text-slate-900">{GLYPH_SEED}</Text>
    </Screen>
  );
}
